/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export const NumberValue = { [key: string]: unknown } as const;
export type Number = typeof NumberValue;
