/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export const ObjectValue = { [key: string]: unknown } as const;
export type Object = typeof ObjectValue;
